version: "3.8"

services:
  fastapi-service:
    build:
      context: .
      dockerfile: python/Dockerfile
    image: joy456/fastapi-service:latest
    container_name: fastapi-service
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    networks:
      - app-network
    restart: unless-stopped

  gin-service:
    build:
      context: .
      dockerfile: go/Dockerfile
    image: joy456/gin-service:latest
    container_name: gin-service
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    networks:
      - app-network
    restart: unless-stopped

  nginx-service:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: joy456/nginx-service:latest
    container_name: nginx-service
    ports:
      - "80:80"
    depends_on:
      - fastapi-service
      - gin-service
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
