# @format

version: "3.8"

services:
  fastapi-service:
    build:
      context: ./python
    image: joy456/fastapi-service:latest
    container_name: fastapi-service
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    networks:
      - app-network
    restart: unless-stopped

  gin-service:
    build:
      context: ./go
    image: joy456/gin-service:latest
    container_name: gin-service
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
