services:
  - name: fastapi-service
    type: web
    env: docker
    dockerfilePath: ./python/Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true

  - name: gin-service
    type: web
    env: docker
    dockerfilePath: ./go/Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true

  - name: nginx-service
    type: web
    env: docker
    dockerfilePath: ./nginx/Dockerfile
    plan: free
    autoDeploy: true
