services:
  - name: fastapi-service
    type: web
    env: docker
    dockerfilePath: ./python/Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ENV
        value: production

  - name: gin-service
    type: web
    env: docker
    dockerfilePath: ./go/Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ENV
        value: production