root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Modify the build command to generate a .exe file
  bin = "./tmp/main.exe"
  cmd = "go build -o ./tmp/main.exe cmd/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  follow_symlink = false
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false